# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: 0.0
os: linux
files:
  - source: src
    destination: /var/www/multi-az-workshop-application
  - source: scripts/kestrel.service
    destination: /etc/systemd/system
permissions:
  - object: /var/www/multi-az-workshop-application/multi-az-workshop-application
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop-kestrel-service.sh
      runas: root
  AfterInstall:
    - location: scripts/enable-kestrel-service.sh
      runas: root
  ApplicationStart:
    - location: scripts/start-kestrel-service.sh
      runas: root
  ValidateService:
    - location: scripts/service-test.sh
      runas: root