# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: docker/stop-container.sh
      runas: root
  BeforeInstall:
    - location: docker/remove-container.sh
      runas: root
  AfterInstall:
    - location: docker/load-container.sh
      runas: root
  ApplicationStart:
    - location: docker/start-container.sh
      runas: root
  ValidateService:
    - location: docker/service-test.sh
      runas: root
  