# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
services:
  multi-az-workshop-application:
    image: multi-az-workshop:latest
    container_name: multi-az-workshop-application
    restart: always
    ports:
      - 5000:5000
    environment:
      - "AWS_EMF_AGENT_ENDPOINT=tcp://cwagent:25888"
      - "AWS_EMF_LOG_STREAM_NAME=${AWS_EMF_LOG_STREAM_NAME}"
      - "DB_SECRET=${DB_SECRET}"
      - "AWS_XRAY_DAEMON_ADDRESS=cwagent:2000"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://cwagent:4318"
  # healthcheck:
  #    test: curl --fail --location http://localhost:5000/health || exit 1
  #    interval: 5s
  #    timeout: 1s
  #    retries: 5
  #    start_period: 10s
  cwagent:
    image: cloudwatch-agent/cloudwatch-agent:latest
    container_name: cwagent
    mem_limit: 256M
    cpus: 0.25
    restart: always
    environment:
      - "CW_CONFIG_CONTENT={\"logs\": {\"metrics_collected\": {\"emf\": { } } }, \"traces\": { \"traces_collected\": {\"xray\": {}, \"otlp\": {} }}}"
