# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
services:
  multi-az-workshop-application:
    image: multi-az-workshop:latest
    container_name: multi-az-workshop-application
    restart: always
    ports:
      - 5000:5000
    environment:
      - "AWS_EMF_AGENT_ENDPOINT=tcp://cwagent:25889"
  # healthcheck:
  #    test: curl --fail --location http://localhost:5000/health || exit 1
  #    interval: 5s
  #    timeout: 1s
  #    retries: 5
  #    start_period: 10s
  cwagent:
    image: cloudwatch-agent/cloudwatch-agent:latest
    container_name: cwagent
    mem_limit: 256M
    cpus: 0.25
    restart: always
    ports: 
      - 25889:25889/tcp
    environment:
      - "CW_CONFIG_CONTENT={\"logs\": {\"metrics_collected\": {\"emf\": { \"service_address\": \"tcp://0.0.0.0:25889\" }}}}"
