# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
services:
  app:
    image: multi-az-workshop/app:latest
    ports:
      - 5000:5000
    healthcheck:
      test: curl --fail --location http://localhost:5000/home || exit 1
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 10s