name: Auto Commit and Approve PR

on:
  push:
    paths:
      - .github/workflows/publish.yml  # Trigger the workflow only if this file changes
    branches:
      - vNext  # You can specify which branches to track

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create_and_approve_pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: vNext

      # Step 2: Set up git
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 3: Create a pull request using GitHub CLI
      - name: Create a PR
        run: |
          # Create the pull request
          gh pr create --base main --head vNext--title "auto update publish workflow" --label "auto-approve"
          gh api -X PATCH /repos/${{ github.repository }}/pulls/${{ env.pr_number }}/merge -f merge_method=merge -f automerge=true
