name: Auto Commit and Approve PR

on:
  push:
    paths:
      - .github/workflows/publish.yml  # Trigger the workflow only if this file changes
    branches:
      - vNext  # You can specify which branches to track

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create_and_approve_pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: vNext

      # Step 2: Set up git
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 3: Create a pull request using GitHub CLI
      - name: Create a PR
        run: |
          # Create the pull request
          gh pr create --title "Auto-update file" --body "This PR automatically updates the file." --base main --head vNext

      # Step 4: Approve the PR using GitHub CLI
      - name: Approve the PR
        run: |
          # Get the PR number
          pr_number=$(gh pr list --state open --head vNext --json number -q ".[0].number")
          
          # Approve the PR
          gh pr review "$pr_number" --approve

      # Step 5: Merge the PR
      - name: Merge the PR
        run: |
          # Get the PR number (same as before)
          pr_number=$(gh pr list --state open --head vNext --json number -q ".[0].number")
          
          # Merge the PR
          gh pr merge "$pr_number" --merge
