name: review

on:
  pull_request_review:
    types: [submitted]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Check if review was approved by specific user
        run: |
            if [[ github.event.review.state == 'approved' && github.event.review.user.login == 'hakenmt' ]]; then
                echo "✅ Test a since review was performed by an allowed user."
            else
                "🚨 Workflow requires admin review approval."
                exit 1
            fi